doctrine:
    dbal:
        connections:
            default:
                url: '%env(DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8
                default_table_options:
                    collate: utf8_general_ci
                schema_filter: ~^(?!view_)~

    orm:
#       auto_generate_proxy_classes: true
        auto_generate_proxy_classes: '%kernel.debug%'
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    WorkHub:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'WorkHub\Entity'
                        alias: WorkHub
