doctrine:
    orm:
        metadata_cache_driver:
            type: service
            pool: doctrine.system_cache_pool
        query_cache_driver:
            type: service
            pool: doctrine.system_cache_pool
        result_cache_driver:
            type: service
            pool: doctrine.result_cache_pool

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
